export const GRAPHILE_WORKER_HANDLER = Symbol('GRAPHILE_WORKER_HANDLER');
export const GRAPHILE_WORKER_CONFIG_TOKEN = Symbol(
  'GRAPHILE_WORKER_CONFIG_TOKEN'
);

export const GRAPHILE_WORKER_UTILS = Symbol('GRAPHILE_WORKER_UTILS');
